export const REQUEST_GET_SIGN_IN_ACTION = "REQUEST_GET_SIGN_IN_ACTION";
export const REQUEST_GET_ALL_DOCUMENTS_ACTION =
  "REQUEST_GET_ALL_DOCUMENTS_ACTION";
export const REQUEST_GET_WHO_AM_I_ACTION = "REQUEST_GET_WHO_AM_I_ACTION";
export const REQUEST_POST_SIGN_UP_ACTION = "REQUEST_POST_SIGN_UP_ACTION";

export const SET_DOCUMENTS_TO_DOCUMENTS_REDUCER_ACTION =
  "SET_DOCUMENTS_TO_DOCUMENTS_REDUCER_ACTION";
export const SET_USER_TO_USER_REDUCER_ACTION =
  "SET_USER_TO_USER_REDUCER_ACTION";
export const SET_ERROR_MESSAGE_TO_ERROR_REDUCER_ACTION =
  "SET_ERROR_MESSAGE_TO_ERROR_REDUCER_ACTION";
